# Generated by Django 2.1.2 on 2018-11-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickers', '0002_clickermultiplequestionsanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickermultiplequestionsanswers',
            old_name='couser_id',
            new_name='course_id',
        ),
    ]
