# Generated by Django 2.1.2 on 2018-12-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orientation',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='orientation',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
