# Generated by Django 2.1.2 on 2018-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('pollurl', models.CharField(blank=True, max_length=255)),
                ('paynowreference', models.CharField(blank=True, max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('requesting_number', models.CharField(blank=True, max_length=255)),
                ('fullname', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
