# Generated by Django 2.1.2 on 2018-10-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.BigIntegerField()),
                ('sortorder', models.BigIntegerField()),
                ('fullname', models.CharField(max_length=254)),
                ('shortname', models.CharField(max_length=255)),
                ('idnumber', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summaryformat', models.IntegerField()),
                ('format', models.CharField(max_length=21)),
                ('showgrades', models.IntegerField()),
                ('newsitems', models.IntegerField()),
                ('startdate', models.BigIntegerField()),
                ('marker', models.BigIntegerField()),
                ('maxbytes', models.BigIntegerField()),
                ('legacyfiles', models.SmallIntegerField()),
                ('showreports', models.SmallIntegerField()),
                ('visible', models.IntegerField()),
                ('visibleold', models.IntegerField()),
                ('groupmode', models.SmallIntegerField()),
                ('groupmodeforce', models.SmallIntegerField()),
                ('defaultgroupingid', models.BigIntegerField()),
                ('lang', models.CharField(max_length=30)),
                ('calendartype', models.CharField(max_length=30)),
                ('theme', models.CharField(max_length=50)),
                ('timecreated', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('requested', models.IntegerField()),
                ('enablecompletion', models.IntegerField()),
                ('completionnotify', models.IntegerField()),
                ('cacherev', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mc_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='McCourseCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('idnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('descriptionformat', models.IntegerField()),
                ('parent', models.BigIntegerField()),
                ('sortorder', models.BigIntegerField()),
                ('coursecount', models.BigIntegerField()),
                ('visible', models.IntegerField()),
                ('visibleold', models.IntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('depth', models.BigIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mc_course_categories',
                'managed': False,
            },
        ),
    ]
